name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for relevant changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src/**'
              - 'src/'

  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yml
    needs: check-for-changes
    if: needs.check-for-changes.outputs.src == 'true' || github.event_name == 'workflow_dispatch'
    with:
      image_name: ghcr.io/${{ github.repository }}
      dockerfile: dockerfile
      build_args: |
        SKIP_BUILD_STATIC_GENERATION=false
        STRAPI_API_URL_PROD=https://api.alemazung.immoly.io
        STRAPI_API_TOKEN_PROD=${{ secrets.STRAPI_API_TOKEN }}
    secrets: inherit

#  deploy-app:
#    runs-on: ubuntu-latest
#    needs: build-and-push
#    permissions:
#      contents: read
#    env:
#      VERSION: ${{ needs.build-and-push.outputs.version }}
#
#    steps:
#      - name: Checkout app-of-apps repo
#        uses: actions/checkout@v4
#        with:
#          repository: davidcode2/app-of-apps
#          token: ${{ secrets.DEPLOYMENT_PAT }}
#
#      - name: Update deployment image tag
#        working-directory: alemazung
#        run: |
#          VERSION=$VERSION
#          DEPLOY_FILE="alemazung-app-deployment.yaml"
#          sed -i "s|image: ghcr.io/davidcode2/dr-joy-alemazung:.*|image: ghcr.io/davidcode2/dr-joy-alemazung:${VERSION}|g" $DEPLOY_FILE
#
#      - name: Commit deployment changes
#        working-directory: alemazung
#        env:
#          GIT_TOKEN: ${{ secrets.DEPLOYMENT_PAT }}
#        run: |
#          git config user.name "github-actions"
#          git config user.email "github-actions@github.com"
#          git config --global credential.helper store
#          echo "https://x-access-token:${GIT_TOKEN}@github.com" > ~/.git-credentials
#          git add .
#          git commit -m "Deploy alemazung website version ${VERSION}"
#          git push
